fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: foo
        sender_name: bar


    resetting:
        email:
            template:   email/password_resetting.email.twig
    registration:
        confirmation:
            template:   '@FOSUser/Registration/email.txt.twig'